export const TOGGLE_IS_LOADING = "TOGGLE_IS_LOADING";
export const TOGGLE_IS_EDITING = "TOGGLE_IS_EDITING";
export const SET_CONTACTS = "SET_CONTACTS";
export const SET_SELECTED_CONTACT_ID = "SET_SELECTED_CONTACT_ID";

export const TOGGLE_IS_DELETE_MODAL_VISIBLE = "TOGGLE_IS_DELETE_MODAL_VISIBLE";
